appName: myhelmapp

port: 80

configmap:
  name: myhelmapp-configmap-v1
  data:
    CUSTOM_HEADER: 'This app was deployed with helm!'

image:
  name: ghcr.io/daveyrpt/flex-url
  tag: latest

nginx:
  replicas: 1
  image:
    name: nginx
    tag: 1.25-alpine