# 2. Nginx Deployment  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flex-url-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flex-url-nginx
  template:
    metadata:
      labels:
        app: flex-url-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.25-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
