apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
      tier: frontend
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        tier: frontend
    spec: # Pod spec
      containers:
      - name: php-fpm
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 9000
        envFrom:
        - configMapRef:
            name: {{ .Values.configmap.name }}
        volumeMounts:
        - name: app-files
          mountPath: /var/www
        resources:
          requests:
            memory: "16Mi" 
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      - name: nginx
        image: {{ .Values.nginx.image.name }}:{{ .Values.nginx.image.tag }}
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: app-files
          mountPath: /var/www
      volumes:
      - name: nginx-config
        configMap:
          name: {{ .Values.appName }}-nginx-config
      - name: app-files
        emptyDir: {}