apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-nginx
  labels:
    app: {{ .Values.appName }}-nginx
spec:
  replicas: {{ .Values.nginx.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}-nginx
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}-nginx
    spec:
      containers:
      - name: nginx
        image: {{ .Values.nginx.image.name }}:{{ .Values.nginx.image.tag }}
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
      - name: nginx-config
        configMap:
          name: {{ .Values.appName }}-nginx-config