apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-nginx
  labels:
    app: {{ .Values.appName }}-nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.appName }}-nginx
  type: NodePort