apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-nginx-config
  labels:
    app: {{ .Values.appName }}
data:
  default.conf: |
    server {
        listen 80;
        root /var/www/public;
        index index.php index.html index.htm;
        
        # Add directory listing for debugging
        autoindex on;
        
        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }
        
        location ~ \.php$ {
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
        }
        
        # Handle static files
        location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
            expires 1y;
            add_header Cache-Control "public, immutable";
        }
    }