apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  ports:
  - port: 9000
    protocol: TCP
    name: php-fpm
  selector:
    app: {{ .Values.appName }}
    tier: frontend
  type: NodePort
